apiVersion: v1
kind: Service

metadata:
  name: spring-data-jpa-mapping-service

spec:
  type: NodePort

  selector:
    app: spring-data-jpa-mapping

  ports:
    - protocol: TCP
      port: 8899
      targetPort: 8899
      nodePort: 30899